name: mealio_dealio
description: An app for planning meals.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  sqflite: ^2.2.5
  path: ^1.8.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.0.0
  build_runner: ^2.3.3
  riverpod_lint: ^1.1.2

flutter:
  uses-material-design: true
